### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by r2hu1**
Here's a detailed breakdown of the corrections i made:

1. URL Corrections:
   - Adjusted URLs to ensure they lead to the correct repositories or web pages. For instance, updated links like `https://github.com/Alex313031/Thorium-Win` to `https://github.com/Alex313031/Thorium-Win-AVX2`, and similar adjustments throughout the document.

2. Markdown Formatting:
   - Reorganized the repository links into markdown format to improve the readability of the document. For example, changed plain text links like `Main repo that hosts the source code for all platforms` to markdown links `[Thorium Main Repository](https://github.com/Alex313031/Thorium)`.

3. Spelling and Grammar:
   - Fixed spelling errors, such as changing "intructions" to "instructions," "Respository" to "Repository," and "important" to the correct spelling.

4. General Improvements:
   - Enhanced readability by refining the content structure and adjusting punctuation for clarity and consistency. For instance, restructuring sentences to read more clearly and separating information for easier comprehension.

These changes were aimed at refining the overall presentation and accuracy of the `README.md` file.

### CODE REVIEW

**Review by gz83 — APPROVED** [review]

**Comment by gz83** [comment]
These changes do not appear to be problematic at first glance, but we still need to wait for Alex to give final approval

@r2hu1 @Alex313031

**Comment by r2hu1** [comment]
> These changes do not appear to be problematic at first glance, but we still need to wait for Alex to give final approval
> 
> @r2hu1 @Alex313031

Sure!

**Comment by r2hu1** [comment]
> These changes do not appear to be problematic at first glance, but we still need to wait for Alex to give final approval
> 
> @r2hu1 @Alex313031

its been almost a day can u review it again and ask alex too.

**Comment by gz83** [comment]
Please be patient with Alex's review, at the moment Alex is busy with personal matters and needs to be away for a while, in the meantime he may not be able to deal with anything inside GitHub or deal with things slower, please understand.

I can help you merge this PR, but I can't do so without Alex's approval.

@r2hu1

**Pull request closed without merging**
